### ISSUE TITLE
mqtt username and password

### ISSUE THREAD

**Issue by ea3hsp** [dh1tw/gorigctl#2]
Is it possible to assign to mqtt server connection a username and password? I'm using my MQTT server with credentials.

'73
EA3HSP
Albert

**Comment by dh1tw** [comment]
Hi Albert,
yes, you can assign a username to the MQTT connection. I think I still haven't implemented password yet. But it should be pretty easy to do so. Let me see if I can add it and create a new build this week.

as for the username - gorigctl uses the flag `user_id` for both, the MQTT connection and within the application for client identification. You can set the `user_id` also in the config file (see gorigctl.toml example in the repository).

```
[general]
user_id = "mycallsign"

```
Tobias

**Comment by dh1tw** [comment]
implemented in [gorigctl 0.1.1](https://github.com/dh1tw/gorigctl/releases). If it works now as expected, feel free to close the issue.
