### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [dh1tw/gorigctl#4]
$ make install-deps

go get github.com/gogo/protobuf/protoc-gen-gofast
go get -u ./...
# github.com/dh1tw/gorigctl/gui
gui/charField.go:10:13: undefined: termui.Attribute
gui/charField.go:12:13: undefined: termui.Align
# github.com/dh1tw/gorigctl/localradio
localradio/localradio.go:19:11: undefined: goHamlib.RIG_VFO_CURR
localradio/localradio.go:21:8: lr.rig.SetDebugLevel undefined (type goHamlib.Rig has no field or method SetDebugLevel)
localradio/localradio.go:23:23: cannot use rigModel (type int) as type goHamlib.RigModelID in argument to lr.rig.Init
localradio/localradio.go:42:10: cannot use vfo (type goHamlib.VFOType) as type int in assignment
localradio/radio.go:51:30: cannot use r.vfo (type int) as type goHamlib.VFOType in argument to r.rig.GetFreq
localradio/radio.go:60:24: cannot use r.vfo (type int) as type goHamlib.VFOType in argument to r.rig.SetFreq
localradio/radio.go:64:36: cannot use r.vfo (type int) as type goHamlib.VFOType in argument to r.rig.GetMode
localradio/radio.go:83:24: cannot use r.vfo (type int) as type goHamlib.VFOType in argument to r.rig.SetMode
localradio/radio.go:97:13: undefined: goHamlib.VfoName
localradio/radio.go:106:11: undefined: goHamlib.VfoValue
localradio/radio.go:106:11: too many errors
# github.com/dh1tw/gorigctl/server
server/deserialize.go:202:16: undefined: goHamlib.VfoValue
server/deserialize.go:215:12: undefined: goHamlib.VfoValue
server/deserialize.go:244:12: undefined: goHamlib.VfoValue
server/deserialize.go:246:21: undefined: goHamlib.OperationValue
server/deserialize.go:280:12: undefined: goHamlib.VfoValue
server/deserialize.go:331:12: undefined: goHamlib.VfoValue
server/deserialize.go:360:12: undefined: goHamlib.VfoValue
server/deserialize.go:377:12: undefined: goHamlib.VfoValue
server/deserialize.go:409:12: undefined: goHamlib.VfoValue
server/deserialize.go:435:12: undefined: goHamlib.VfoValue
server/deserialize.go:435:12: too many errors
# github.com/dh1tw/gorigctl/radioserver
radioserver/server.go:69:7: r.rig.SetDebugLevel undefined (type goHamlib.Rig has no field or method SetDebugLevel)
radioserver/server.go:71:22: cannot use rs.RigModel (type int) as type goHamlib.RigModelID in argument to r.rig.Init
radioserver/server.go:122:5: r.deserializeCatRequest undefined (type localRadio has no field or method deserializeCatRequest)
radioserver/server.go:165:25: r.rig.GetPowerStat undefined (type goHamlib.Rig has no field or method GetPowerStat)
radioserver/server.go:170:16: undefined: goHamlib.RIG_POWER_ON
radioserver/server.go:187:10: undefined: goHamlib.VfoValue
radioserver/server.go:194:26: undefined: goHamlib.VfoName
radioserver/server.go:262:25: undefined: goHamlib.VfoName
radioserver/server.go:358:19: r.serializeCaps undefined (type *localRadio has no field or method serializeCaps)
radioserver/server.go:386:9: undefined: goHamlib.VfoValue
radioserver/server.go:386:9: too many errors
make: *** [install-deps] Error 2

**Comment by dh1tw** [comment]
Hi, 
indeed, this project does not compile. The underlying GUI library has unfortunately changed significantly. At the moment I have kinda abounded this project because, apart of the API changes of the GUI library, there are also some major flaws with concurrency with that library.
